### ISSUE TITLE
add_pet_buddy

### ISSUE THREAD

**Issue by oawanis** [karimFarid/CloudPet-BTQ-#12]
A pet buddy is assigned to a pet and have privileges concerning the actions they can take towards the pet (feed and/or edit schedule). They can be added in the pet's page

**Comment by oawanis** [comment]
pushed pet buddy model

**Comment by oawanis** [comment]
please review @AhmadHatem @hosamhany @karimFarid

**Comment by karimFarid** [comment]
Reviewed , and merged!

**Comment by oawanis** [comment]
![7751189](https://cloud.githubusercontent.com/assets/10798231/7055119/c6272c46-de49-11e4-943a-d76d0437b405.png)
