### ISSUE TITLE
feeding_schedule

### ISSUE THREAD

**Issue by mohamed-moubarak** [karimFarid/CloudPet-BTQ-#15]
A user can create, View and delete pet's feeding schedule.

**Comment by mohamed-moubarak** [comment]
@omarwanis @hossamhany @youssefadel94 please review the code.

**Comment by mohamed-moubarak** [comment]
@omarwanis @hossamhany @youssefadel94 please review.

**Comment by oawanis** [comment]
code reviewed 👍

**Comment by youssefadel94** [comment]
good work

**Comment by hosamhany** [comment]
scenario reviewed 🐧

**Comment by karimFarid** [comment]
![11122078_10153021044297935_1181583815_n](https://cloud.githubusercontent.com/assets/10815562/7057856/df6e3c1a-de5a-11e4-9038-152fb7b2f85c.jpg)

The UML u sent me, i forgot to ask you to post it.
