### ISSUE TITLE
view my buddies and view buddy's pet

### ISSUE THREAD

**Issue by AhmadHatem** [karimFarid/CloudPet-BTQ-#19]
user can see his buddies and delete a buddy or edit ,and user who is a pet buddy for another user can see his buddy's pets and unlink himself from being a buddy.

**Comment by AhmadHatem** [comment]
please review @omarwanis , @hosamhany , @karimFarid

**Comment by oawanis** [comment]
Documentation reviewed 🐧

**Comment by hosamhany** [comment]
Test & scenario reviewed 🐧

**Comment by AhmadHatem** [comment]
deleting a buddy and deleting a buddy's pet
![deleting_pet_and_buddy](https://cloud.githubusercontent.com/assets/10855948/7054949/c907e2bc-de48-11e4-979e-3cb47a05ee4e.png)

**Comment by AhmadHatem** [comment]
list of my buddies and list of buddy's pet
![list_of_buddies_and_buddy_s_pet](https://cloud.githubusercontent.com/assets/10855948/7054967/e39ec2da-de48-11e4-8831-6032ce086ca4.png)
